In [2]:
# import pandas module 
import pandas as pd 
  
# making dataframe 
df = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv") 
  
# it was print the first 5-rows 
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [6]:
df_stacked = df.stack()
df_stacked.head(20)

0  Name         Avery Bradley
   Team        Boston Celtics
   Number                   0
   Position                PG
   Age                     25
   Height                 6-2
   Weight                 180
   College              Texas
   Salary         7.73034e+06
1  Name           Jae Crowder
   Team        Boston Celtics
   Number                  99
   Position                SF
   Age                     25
   Height                 6-6
   Weight                 235
   College          Marquette
   Salary         6.79612e+06
2  Name          John Holland
   Team        Boston Celtics
dtype: object

In [7]:
df_unstacked = df_stacked.unstack() 
df_unstacked.head(20)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7.73034e+06
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6.79612e+06
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1.14864e+06
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,NaN,5e+06
5,Amir Johnson,Boston Celtics,90,PF,29,6-9,240,NaN,1.2e+07
6,Jordan Mickey,Boston Celtics,55,PF,21,6-8,235,LSU,1.17096e+06
7,Kelly Olynyk,Boston Celtics,41,C,25,7-0,238,Gonzaga,2.16516e+06
8,Terry Rozier,Boston Celtics,12,PG,22,6-2,190,Louisville,1.82436e+06
9,Marcus Smart,Boston Celtics,36,PG,22,6-4,220,Oklahoma State,3.43104e+06
10,Jared Sullinger,Boston Celtics,7,C,24,6-9,260,Ohio State,2.56926e+06
11,Isaiah Thomas,Boston Celtics,4,PG,27,5-9,185,Washington,6.91287e+06
12,Evan Turner,Boston Celtics,11,SG,27,6-7,220,Ohio State,3.42551e+06
13,James Young,Boston Celtics,13,SG,20,6-6,215,Kentucky,1.74984e+06
14,Tyler Zeller,Boston Celtics,44,C,26,7-0,253,North Carolina,2.61698e+06
15,Bojan Bogdanovic,Brooklyn Nets,44,SG,27,6-8,216,NaN,3.42551e+06
16,Markel Brown,Brooklyn Nets,22,SG,24,6-3,190,Oklahoma State,845059
17,Wayne Ellington,Brooklyn Nets,21,SG,28,6-4,200,North Carolina,1.5e+06
18,Rondae Hollis-Jefferson,Brooklyn Nets,24,SG,21,6-7,220,Arizona,1.33548e+06
19,Jarrett Jack,Brooklyn Nets,2,PG,32,6-3,200,Georgia Tech,6.3e+06

In [8]:
df_unstacked = df.unstack()
df_unstacked.head(20)

Name  0               Avery Bradley
      1                 Jae Crowder
      2                John Holland
      3                 R.J. Hunter
      4               Jonas Jerebko
      5                Amir Johnson
      6               Jordan Mickey
      7                Kelly Olynyk
      8                Terry Rozier
      9                Marcus Smart
      10            Jared Sullinger
      11              Isaiah Thomas
      12                Evan Turner
      13                James Young
      14               Tyler Zeller
      15           Bojan Bogdanovic
      16               Markel Brown
      17            Wayne Ellington
      18    Rondae Hollis-Jefferson
      19               Jarrett Jack
dtype: object